### ISSUE TITLE
Handle Large Datasets in Export to FireCloud

### ISSUE THREAD

**Issue by coverbeck** [DataBiosphere/dcc-dashboard-service#11]
Currently, we take all the selected data and put it into a bagit, and send that bagit to the lamba which sends it to FC.

We could instead create multiple bagits, of smaller sizes.

This would get us around the potential lambda timeout issue.

**Comment by cricketsloan** [comment]
This ticket is being consolidated with the other dcc-dashboard tickets
it is now tracked in https://github.com/BD2KGenomics/dcc-dashboard-service/issues/68
