### ISSUE TITLE
Retry failed HTTP requests when exporting to FireCloud

### ISSUE THREAD

**Issue by mikebaumann** [DataBiosphere/dcc-dashboard-service#12]
Currently when exporting to FireCloud (via the `bagit_to_firecloud` Lambda, the HTTP requests are only tried once, and if it fails, the export fails.
There are many cases in an HTTP request can fail and a subsequent retry will succeed, and to have a reliable/robust system, retry is essential.

There are a variety of ways to implement retrying operations.
It looks like the `requests` package does provide retry support, so that may be a good option.
Another option to consider is the @retry decorated developed by the HCA `data-store` team, here: https://github.com/HumanCellAtlas/data-store/blob/master/dss/util/retry.py

**Comment by coverbeck** [comment]
Note that the error seen in a demo was not in exporting; it was seen in bringing up the dialog where the user specifies the inputs for the export. To bring up the dialog, the UI makes 2 API calls to FireCloud to get the user's workspaces and billing projects, and either of those APIs would sometimes fail. Retrying those calls seems to get around the failure.

This has been addressed in https://github.com/DataBiosphere/boardwalk/commit/d7694831656b3c76bfc12226d8cd3cff367dd68d -- we are now doing up to 5 retries from the browser.

For the actual export to FireCloud, which makes API calls to optionally create the workspace and export the data, the need for those changes is covered by DataBiosphere/bagit-firecloud-lambda#9
